spring:
  jdbc:
    initialize-schema: never
  datasource:
    url: jdbc:mariadb://${DB_URL}/hotel-java?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&passwordCharacterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  security:
    enabled: true
  thymeleaf:
    cache: true
  jpa:
    hibernate:
      ddl-auto: create-drop # 임시 테스트로 create-drop
    properties:
      hibernate:
        use_sql_comment: true
        show_sql: true
        format_sql: true
        highlight_sql: true

logging.level:
  p6spy: info
  org.hibernate.SQL: info
  org.hibernate.type: info
  org.springframework:
    batch: info
    security.web: info
